---
- name: Git clone acme-assembly-vscode-template
  git:
    repo=https://github.com/Esshahn/acme-assembly-vscode-template
    dest='{{ WORKSPACE_DIR }}/acme-assembly-vscode-template'

- name: Git clone OldSkoolCoder tutorials
  git:
    repo=https://github.com/rodoherty1/6502-Examples
    dest='{{ WORKSPACE_DIR }}/6502-Examples'

- name: Git clone SlithyMatt/x16-assembly-tutorial
  git:
    repo=https://github.com/SlithyMatt/x16-assembly-tutorial
    dest='{{ WORKSPACE_DIR }}/x16-assembly-tutorial'

- name: "Create CC65 c64-adm.cfg link"
  file:
    src: /usr/share/cc65/cfg/c64-asm.cfg
    dest: '{{ WORKSPACE_DIR }}/6502-Examples/c64-adm.cfg'
    state: link
